apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: g-rag-ingress
  namespace: g-rag
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: app.g-rag.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: g-rag-frontend-svc
            port:
              number: 80
  - host: api.g-rag.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: g-rag-backend-svc
            port:
              number: 80
